
<footer>
    <div id="footerone">
        <h2>Contact Us</h2><br>

        Dhanmondi,83 no. xxx Road, Mohammadpur<br>
        Tel: +8801629990000
    </div>

    <div id="footertwo">
        <h2>LIKE US ON FACEBOOK</h2>

    </div>

    <div id="footerthree">
        <h2>NEWSLETTER</h2> <br>
        Join our mailing list to receive news and announcements<br>
        <input type="text"> <br>
        <Button>Subscribe</Button>
    </div>

</footer>