

<header >

    <nav >
        <a href = "index.php" > Home</a >
        <a href = "jobs.php" > Job</a >
        <a href = "apply.php" > Apply</a >
        <a href = "about.php" > About Me </a >
        <a href = "manage.php" > Manage </a >
        <a href = "enhancements.php" > Enhancement</a >
        <a href = "enhancements2.php" > Enhancement2</a >
        <a href = "enhancements3.php" > Manange2</a >
         <a href = "store_job.php" >Job2</a >
        <a href = "phpenhancements.php" >phpEnhancement</a >
        
        <img class="logo" src = "images/logo.png" alt = "Logo of REVE" >
    </nav >
</header >


